### ISSUE TITLE
Docs improvements for noobs

### ISSUE THREAD

**Issue by erictune** [kubernetes-sigs/kubebuilder#1031]
Make quick start friendly for someone new to Go.  They may be using Go for the first time to write an operator.

In https://kubebuilder.io/quick-start.html:
- [x] Explain that go language is required to use as the language for KubeBuilder.
- [x] Suggest min golang version to have installed.
- [ ] suggest making a directory for the project under `$GOPATH/src` such as `$GOPATH/src/kb-quickstart` 
- [ ] clarify that `kubebuilder init --domain my.domain` needs to be run from `$GOPATH/src/$MODULE` rather than from ` $GOPATH`.  The latter is sort of implied by the sentence _If you’re not in GOPATH, you’ll need to ..._

**Comment by camilamacedo86** [comment]
The following suggestions:

>  suggest making a directory for the project under $GOPATH/src such as $GOPATH/src/kb-quickstart
>  clarify that kubebuilder init --domain my.domain needs to be run from $GOPATH/src/$MODULE rather than from $GOPATH. The latter is sort of implied by the sentence If you’re not in GOPATH, you’ll need to ...

I am not sure if are required since is not really more mandatory have the GOPATH since it is using models. However, the other one 100% agree.

**Comment by erictune** [comment]
Suggest that quickstart doc should focus on providing complete steps that
will work.
Whether something is required or not isn't as important.

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12 and @erictune, 

I think we can close it with the merge of PR: #1008. The quick was improved and may is not exactly as you suggested here but I think that it is covering now your main concerns raised here. WDYT? Can we close this one?

**Comment by erictune** [comment]
That PR addresses my first two comments, which I've checked off in the top post.
Thanks for the quick fix.

PR #1008 didn't seem to address my last two suggestions.  I'll let others decide if those are important enough to keep issue open or not.

**Comment by camilamacedo86** [comment]
Hi @erictune, 

The lastest 2 suggestions in POV are addressed in the notes as follows.
- https://github.com/kubernetes-sigs/kubebuilder/pull/1008/files#diff-e7f384593803dbfd8186105c2163ede5R51
- https://github.com/kubernetes-sigs/kubebuilder/pull/1008/files#diff-e7f384593803dbfd8186105c2163ede5R59

However, the users should be able to do the project where they wish. Maybe we could add the link <https://golang.org/doc/code.html#GOPATH> in the notes for a further understanding.  WDYT?

**Comment by erictune** [comment]
Those are good additions.  I meant something slightly different.

This command sequence is "in GOPATH" but gives an error:
```
~/ $ cd $GOPATH
~/go/ $ kubebuilder init
2019/10/05 08:00:28 error finding current repository ...
```
Running the `go mod init` command suggested doesn't fix it.  If I do verbatim what the docs suggest, I still get an error:
```
~/ $ cd $GOPATH
~/go $ go mod init example.com/m
~/go $ kubebuilder init
2019/10/05 08:04:13 error finding current repository: could not determine repository path from module data, package data, or by initializing a module: go mod init: go.mod already exists
```

The commands I would suggest are:
```
$ mkdir $GOPATH/src/kbexample
$ cd $GOPATH/src/kbexample
$ kubebuilder
```

**Comment by camilamacedo86** [comment]
Hi @erictune, 

I understand that it as addressed in the following explanation. 

```
**Create a directory**, and then run the following command inside of it to initialize a new project:

kubebuilder init --domain my.domain 
```

**Comment by camilamacedo86** [comment]
Hi @erictune, 

Also,I did a new PR to cover these points. Please, see #1076 and let me know if we can agree in close this one with or if it has anything else more that you would like to address.
